name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master  # Or main if you're using that

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBDEVSITE_E96C6 }}
          channelId: live
          projectId: webdevsite-e96c6
          entryPoint: .
